#!/usr/bin/env python3
"""Fill D-04 详细设计说明书 - preserve formatting, use 「」 for quotes."""

from docx import Document
from docx.shared import Pt
from copy import deepcopy
import glob, os

matches = glob.glob("/Users/taohaoran/Documents/git/Software-Engineering/产出模板/D-04_*模板.docx")
SRC = matches[0]
DST = "/Users/taohaoran/Documents/git/Software-Engineering/NekoCafe/submission/G03_T-01_D-04_详细设计说明书_v1.0.docx"

doc = Document(SRC)

def cs(cell, text):
    for p in cell.paragraphs: p.clear()
    for p in cell.paragraphs[1:]: p._element.getparent().remove(p._element)
    cell.paragraphs[0].text = ""
    r = cell.paragraphs[0].add_run(text)
    r.font.name = "Microsoft YaHei"; r.font.size = Pt(10)

def cm(cell, lines):
    for p in cell.paragraphs: p.clear()
    for p in cell.paragraphs[1:]: p._element.getparent().remove(p._element)
    for i, line in enumerate(lines):
        if i == 0: p = cell.paragraphs[0]
        else:
            new_el = deepcopy(cell.paragraphs[0]._element)
            cell._element.append(new_el)
            p = cell.paragraphs[i]
        p.clear()
        r = p.add_run(line)
        r.font.name = "Microsoft YaHei"; r.font.size = Pt(10)

# ── Cover metadata ──
t = doc.tables[0]
cs(t.cell(4,1), "第 3 组")
cs(t.cell(5,1), "计算机22-3 / 221234301 / 张某某\n计算机22-3 / 221234302 / 李某某\n计算机22-3 / 221234303 / 王某某\n计算机22-3 / 221234304 / 赵某某")
cs(t.cell(6,1), "2026 - 06 - 13")

# ═══════ D-04 TABLE MAP ═══════
# T0: metadata | T1: guidance | T2: cover info | T3: section 1 heading
# T4: section 1 引言 body (placeholder)
# T5: section 2.1 代码规范 | T6: section 2.2 公共数据结构 (guided) | T7: section 2.3 公共工具类
# T8: section 2 footer (placeholder)
# T9: section 3.1 guided | T10: section 3.2 | T11: section 3.3
# T12: section 3 footer (placeholder)
# T13: section 4.1 | T14: section 4.2
# T15: section 4 footer (placeholder)
# T16: section 5.1 | T17: section 5.2
# T18: section 5 footer (placeholder)
# T19: section 6 | T20: section 7 (guided)

# Section 1: 引言 (T4)
cm(doc.tables[4].cell(0,0), [
    "1.1 编写目的",
    "本文档是 NekoCafé 智慧猫咖餐饮预约平台的详细设计说明书，描述每个模块的内部类结构、关键算法、核心时序和数据流转。目标读者为开发团队，须能让一位中等水平的开发者根据本文档独立编码实现对应模块。",
    "",
    "1.2 本文档与概要设计的衔接",
    "本文档是 D-03 概要设计说明书的下游细化文档：",
    "• D-03 §3 系统结构（16 个领域包）→ 本文档 §3 模块详细设计（选取 5 个核心模块展开）",
    "• D-03 §4 运行视图（顺序图+状态机）→ 本文档 §5 类与时序图（细化到类级别）",
    "• D-03 §8 接口设计（API 端点）→ 本文档 §3 各模块的 Controller 层实现细节",
    "• D-03 ADR 决策 → 本文档 §6 异常处理与并发设计（ADR 方案落地）"
])

# Section 2: 全局约定 (T5, T6, T7, T8)
cm(doc.tables[6].cell(0,0), [
    "2.1 代码规范",
    "后端 (Java)：",
    "• 命名：类名 PascalCase、方法/变量 camelCase、常量 UPPER_SNAKE_CASE",
    "• 包结构：com.nekocafe.{domain}.{layer}（如 com.nekocafe.order.service）",
    "• Controller 方法使用 @PreAuthorize 注解标明角色权限",
    "• Service 层方法抛出 BizException（code + 中文 message），不返回 null",
    "• Mapper 层使用 MyBatis-Plus BaseMapper，复杂查询使用 LambdaQueryWrapper",
    "• 实体类不使用 Lombok（团队约定），手写 getter/setter",
    "",
    "前端 (Vue 3 + TypeScript)：",
    "• 组件命名：PascalCase（如 CustomerHomeView.vue）",
    "• 组合式 API（<script setup lang=\\\"ts\\\">）",
    "• API 调用统一通过 src/api/ 下的模块封装，不在组件中直接使用 axios",
    "• 类型定义集中在 src/types/ 下",
    "",
    "2.2 公共数据结构",
    "ApiResult<T>（统一 API 响应封装）：",
    "  {",
    "    code: Integer,     // 0=成功, 其他=业务错误码",
    "    message: String,   // 中文提示信息",
    "    data: T,           // 泛型数据载荷",
    "    traceId: String,   // 请求追踪 ID (UUID)",
    "    timestamp: Long    // 响应时间戳",
    "  }",
    "",
    "PageRequest（统一分页请求）：",
    "  { page: Integer (>=1), size: Integer (1-100, default 10) }",
    "",
    "PageResponse<T>（统一分页响应）：",
    "  { page: Integer, size: Integer, total: Long, records: List<T> }",
    "",
    "AuthPrincipal（JWT 解析后的用户身份）：",
    "  { userId: Long, username: String, nickname: String, roles: List<String> }",
    "  通过 @AuthenticationPrincipal 注解在 Controller 方法参数中注入",
    "",
    "BizException（统一业务异常）：",
    "  { code: int, message: String }",
    "  由 GlobalExceptionHandler (@RestControllerAdvice) 统一捕获并转换为 ApiResult",
    "",
    "2.3 公共工具类",
    "• JwtService：Token 生成（HMAC-SHA256）、解析、校验过期",
    "• MybatisPlusConfig：注册乐观锁拦截器、分页拦截器",
    "• WebMvcConfig：静态资源映射（上传文件访问路径）",
    "• GlobalExceptionHandler：统一异常 → ApiResult 转换",
    "• 雪花 ID：MyBatis-Plus 内置雪花算法生成分布式唯一 ID（实体主键）"
])

cs(doc.tables[8].cell(0,0),
    "以上全局约定了代码规范、公共数据结构和公共工具类，为所有模块的详细设计和编码提供统一基础。")

# Section 3: 模块详细设计 (T9, T10, T11, T12) - 5 core modules
cm(doc.tables[9].cell(0,0), [
    "以下选取 5 个核心模块展开详细设计：",
    "",
    "═══════════════════════════════════════════",
    "模块 A：reservation（预约管理模块）",
    "═══════════════════════════════════════════",
    "包结构：com.nekocafe.reservation",
    "├── controller/ReservationController.java",
    "├── service/ReservationService.java",
    "├── service/ReservationSlotGenerator.java",
    "├── entity/Reservation.java, ReservationSlot.java",
    "└── mapper/ReservationMapper.java, ReservationSlotMapper.java",
    "",
    "核心类职责：",
    "• ReservationController：对外暴露 REST 端点（@PreAuthorize(hasRole('CUSTOMER'))）",
    "  - GET /api/reservation/slots — 查询可用时段",
    "  - POST /api/reservation — 创建预约",
    "  - GET /api/reservation/me — 我的预约列表",
    "  - POST /api/reservation/{id}/cancel — 取消预约",
    "",
    "• ReservationService：核心业务逻辑",
    "  - create(ReservationRequest, userId)：",
    "    1. 查询 DiningTable，校验 partySize <= capacity",
    "    2. 查询 ReservationSlot，校验 availableCount > 0 且 status=AVAILABLE",
    "    3. 条件更新扣减库存（乐观锁）：",
    "       UPDATE reservation_slot",
    "       SET available_count = available_count - 1,",
    "           reserved_count = reserved_count + 1,",
    "           version = version + 1",
    "       WHERE id = #{slotId} AND available_count > 0",
    "    4. 若 affected_rows=0 → BizException(3004, 「该时段已约满」)",
    "    5. INSERT INTO reservation (...) VALUES (...)",
    "    6. 返回 Reservation 详情",
    "  - cancel(reservationId, userId)：",
    "    1. 校验预约归属本人",
    "    2. 校验状态为 RESERVED（已签到不可取消）",
    "    3. 恢复库存：UPDATE reservation_slot SET available_count = available_count + 1, reserved_count = reserved_count - 1 WHERE id = #{slotId}",
    "    4. UPDATE reservation SET status = 'CANCELLED'",
    "",
    "关键算法：乐观锁并发控制（见 §4.1）",
    "",
    "═══════════════════════════════════════════",
    "模块 B：order（订单管理模块）",
    "═══════════════════════════════════════════",
    "包结构：com.nekocafe.order",
    "├── controller/OrderController.java",
    "├── service/OrderService.java",
    "├── entity/FoodOrder.java, FoodOrderItem.java",
    "└── mapper/FoodOrderMapper.java, FoodOrderItemMapper.java",
    "",
    "核心类职责：",
    "• OrderController：@PreAuthorize(hasRole('CUSTOMER'))",
    "  - POST /api/order — 创建订单",
    "  - GET /api/order/me — 我的订单",
    "  - POST /api/order/{id}/cancel — 取消订单",
    "",
    "• OrderService：核心业务逻辑",
    "  - create(OrderRequest, userId)：",
    "    1. 逐项校验：Dish 存在、status=ON_SHELF、storeId 匹配",
    "    2. 逐项校验：dish.stock >= item.quantity",
    "    3. @Transactional 事务中：",
    "       a) 条件扣减每项菜品库存：",
    "          UPDATE dish SET stock = stock - #{quantity}",
    "          WHERE id = #{dishId} AND stock >= #{quantity}",
    "       b) 若任一扣减失败 → BizException(3005, dishName + 「库存不足」)",
    "       c) 计算金额：totalAmount = sum(price * quantity)",
    "       d) 优惠券抵扣：payableAmount = totalAmount - couponDiscount",
    "       e) INSERT food_order + food_order_item",
    "    4. 返回 FoodOrder 详情",
    "  - cancel(orderId, userId)：校验归属 + 仅 CREATED 状态可取消",
    "",
    "订单状态字段：status IN (CREATED, PAID, PREPARING, COMPLETED, CANCELLED, REFUNDING, REFUNDED, REFUND_REJECTED)",
    "",
    "═══════════════════════════════════════════",
    "模块 C：payment（支付模块）",
    "═══════════════════════════════════════════",
    "包结构：com.nekocafe.payment",
    "├── controller/PaymentController.java",
    "├── service/PaymentService.java",
    "├── entity/PaymentRecord.java",
    "└── mapper/PaymentRecordMapper.java",
    "",
    "• PaymentService.sandboxPay(orderId, idempotencyKey, userId)：",
    "  1. 校验订单归属：order.userId == userId",
    "  2. 幂等检查：SELECT * FROM payment_record WHERE idempotency_key = #{key}",
    "     若已有 SUCCESS 记录 → 直接返回已有 PaymentRecord（幂等）",
    "  3. 生成 paymentNo (雪花ID)",
    "  4. INSERT payment_record (paymentNo, orderId, idempotencyKey, amount, channel=SANDBOX, status=SUCCESS)",
    "  5. UPDATE food_order SET status = 'PAID' WHERE id = #{orderId}",
    "  6. 积分发放：UPDATE member_account SET points = points + #{earnedPoints} WHERE user_id = #{userId}",
    "  7. 会员等级更新（根据累计积分判断）",
    "  8. INSERT points_transaction（积分流水）",
    "",
    "支付幂等保证：idempotencyKey = orderId + timestamp，唯一索引约束 + 业务查重双保险。",
    "",
    "═══════════════════════════════════════════",
    "模块 D：recommend（推荐引擎模块）",
    "═══════════════════════════════════════════",
    "包结构：com.nekocafe.recommend",
    "├── controller/RecommendController.java",
    "├── service/RecommendService.java",
    "├── service/RecommendationReasonGenerator.java",
    "├── ai/OpenAiCompatibleReasonClient.java",
    "├── ai/AiReasonProperties.java",
    "├── dto/RecommendationFeedResponse.java, RecommendationCatFeedResponse.java",
    "└── dto/RecommendationStoreItem.java, RecommendationCatItem.java",
    "",
    "两阶段推荐架构：",
    "  阶段1-规则评分（核心，始终可用）：",
    "    1. 读取 UserPreference（偏好类型/值）",
    "    2. 对每个门店计算多维得分：",
    "       - 偏好匹配分：门店特征与用户偏好的余弦相似度",
    "       - 距离分：1 / (1 + distanceKm)（LBS 加权）",
    "       - 活跃分：门店活动/优惠券数量加权",
    "       - 猫咪匹配分：门店猫咪性格与用户偏好的匹配度",
    "    3. 综合得分 = w1*偏好分 + w2*距离分 + w3*活跃分 + w4*猫咪分",
    "    4. 按得分降序排列，取 Top 5",
    "  阶段2-AI文案（可选，增强体验）：",
    "    1. 若 ai.enabled=true 且 apiKey 有效",
    "    2. 调用 OpenAI 兼容 API 生成中文推荐理由",
    "    3. 若调用失败或 disabled → fallback 模板文案",
    "",
    "推荐理由 fallback 模板：",
    "  「根据您的偏好，推荐 {storeName} 的 {area} 区域。」",
    "  「{catName}（{breed}，性格{personality}）适合与您互动。」",
    "",
    "═══════════════════════════════════════════",
    "模块 E：customer（顾客门户模块）",
    "═══════════════════════════════════════════",
    "包结构：com.nekocafe.customer",
    "├── controller/CustomerController.java",
    "├── service/CustomerService.java",
    "├── service/RewardRedemptionService.java",
    "├── entity/UserPreference.java, Review.java, RefundRequest.java,",
    "│   RewardCatalog.java, RewardRedemption.java, PointsTransaction.java",
    "└── mapper/（6 个 Mapper）",
    "",
    "核心功能：",
    "• 顾客首页 (GET /customer/home)：聚合门店推荐、活动列表、订单概览",
    "• 积分系统：",
    "  - GET /customer/points — 积分余额 + 流水",
    "  - GET /customer/rewards — 可兑换奖励列表（含等级门槛）",
    "  - POST /customer/rewards/{id}/redeem — 兑换奖励（扣减积分，幂等防重）",
    "• 偏好管理：GET/PUT /customer/preferences — 用户偏好（类型-值对）",
    "• 评价系统：POST /customer/orders/{id}/reviews — 评价订单（含评分+内容）",
    "• 退款申请：POST /customer/orders/{id}/refunds — 创建退款申请（REFRESH → REQUESTED），校验订单归属+状态+非重复申请",
    "• 活动领取：POST /customer/activities/{id}/claim — 领取活动优惠券（唯一索引防重）"
])

cs(doc.tables[12].cell(0,0),
    "以上 5 个核心模块的详细设计覆盖了预约、订单、支付、推荐和顾客门户的包结构、核心类职责和关键方法实现逻辑，为编码提供完整指导。")

# Section 4: 关键算法描述 (T13, T14, T15)
cm(doc.tables[13].cell(0,0), [
    "4.1 算法 1：预约并发控制（乐观锁库存扣减）",
    "",
    "应用场景：高峰期 1000 并发预约同一时段的同一桌位类型。",
    "",
    "伪代码：",
    "  function createReservation(slotId, partySize, userId):",
    "    // 1. 读取当前数据（非锁定读）",
    "    slot = reservationSlotMapper.selectById(slotId)",
    "    if slot.availableCount <= 0:",
    "        throw BizException(3004, 「该时段已约满」)",
    "",
    "    // 2. 乐观锁条件更新",
    "    updateWrapper = new LambdaUpdateWrapper<ReservationSlot>()",
    "        .eq(ReservationSlot::getId, slotId)",
    "        .gt(ReservationSlot::getAvailableCount, 0)",
    "        .setSql(\\\"available_count = available_count - 1\\\")",
    "        .setSql(\\\"reserved_count = reserved_count + 1\\\")",
    "        .setSql(\\\"version = version + 1\\\")",
    "    affected = reservationSlotMapper.update(null, updateWrapper)",
    "",
    "    // 3. 检查结果",
    "    if affected == 0:",
    "        throw BizException(3005, 「预约冲突，请重试」)",
    "",
    "    // 4. 创建预约记录",
    "    reservation = new Reservation(...)",
    "    reservationMapper.insert(reservation)",
    "    return reservation",
    "",
    "复杂度：O(1) — 单条 UPDATE + INSERT，无锁等待",
    "边界条件：",
    "  • 库存为 0：.gt(availableCount, 0) 条件阻止超卖",
    "  • 并发冲突：MyBatis-Plus 乐观锁自动版本校验（version 字段），失败重试",
    "  • 重复预约：同一用户同一时段唯一索引防重",
    "",
    "4.2 算法 2：推荐评分算法（多维度加权排序）",
    "",
    "应用场景：为顾客个性化推荐门店、桌位和猫咪。",
    "",
    "伪代码：",
    "  function scoreStore(userId, store):",
    "    prefs = userPreferenceMapper.selectByUserId(userId)",
    "",
    "    // 偏好匹配分 (0-100)",
    "    prefScore = 0",
    "    for pref in prefs:",
    "        if store.tags.contains(pref.value) or store.area == pref.value:",
    "            prefScore += 25  // 每个匹配加 25 分",
    "    prefScore = min(prefScore, 100)",
    "",
    "    // 距离分 (0-100)",
    "    if userLat != null and userLng != null:",
    "        distance = haversine(userLat, userLng, store.lat, store.lng)",
    "        distanceScore = 100 / (1 + distance)  // 距离越近分越高",
    "    else:",
    "        distanceScore = 50  // 无位置信息时默认中间分",
    "",
    "    // 活跃分 (0-100)",
    "    activeActivityCount = countActiveActivities(store.id)",
    "    activityScore = min(activeActivityCount * 20, 100)",
    "",
    "    // 猫咪匹配分 (0-100)",
    "    cats = catMapper.selectByStoreId(store.id)",
    "    catScore = 0",
    "    for cat in cats:",
    "        for pref in prefs:",
    "            if cat.personality == pref.value or cat.breed == pref.value:",
    "                catScore += 30",
    "    catScore = min(catScore, 100)",
    "",
    "    // 加权综合",
    "    return 0.35*prefScore + 0.25*distanceScore + 0.15*activityScore + 0.25*catScore",
    "",
    "复杂度：O(S * P * C) — S=门店数(~50), P=偏好数(~5), C=猫咪数(~10) → 约 2500 次比较，毫秒级",
    "边界条件：",
    "  • 无偏好数据：偏好分=50（默认值）",
    "  • 无位置数据：距离分=50（默认值）",
    "  • 门店无猫咪：猫咪分=0（不影响其他维度）"
])

cs(doc.tables[15].cell(0,0),
    "以上两个关键算法的详细设计覆盖了预约并发控制和推荐评分的核心实现逻辑、复杂度分析与边界条件处理。")

# Section 5: 类与时序图 (T16, T17, T18)
cm(doc.tables[16].cell(0,0), [
    "5.1 核心类图",
    "",
    "预约域核心类图：",
    "┌─────────────────────────┐",
    "│  ReservationController  │",
    "│  + create(req, user)    │",
    "│  + cancel(id, user)     │",
    "│  + getSlots(storeId)    │",
    "│  + getMyReservations()  │",
    "└───────────┬─────────────┘",
    "            │ uses",
    "┌───────────▼─────────────┐",
    "│   ReservationService    │",
    "│  + create(req, userId)  │",
    "│  + cancel(id, userId)   │",
    "│  + getAvailableSlots()  │",
    "│  + listByUserId()       │",
    "└───┬──────────────┬──────┘",
    "    │ uses         │ uses",
    "┌───▼──────────┐ ┌▼────────────────┐",
    "│Reservation   │ │ReservationSlot  │",
    "│Mapper        │ │Mapper           │",
    "│(MyBatisPlus) │ │(MyBatisPlus)    │",
    "└──────────────┘ └─────────────────┘",
    "",
    "订单域核心类图：",
    "┌─────────────────────────┐",
    "│    OrderController      │",
    "│  + create(req, user)    │",
    "│  + cancel(id, user)     │",
    "│  + getMyOrders()        │",
    "└───────────┬─────────────┘",
    "            │ uses",
    "┌───────────▼─────────────┐       ┌────────────────────┐",
    "│     OrderService        │──────>│   PaymentService   │",
    "│  + create(req, userId)  │       │  + sandboxPay(...) │",
    "│  + cancel(id, userId)   │       └────────────────────┘",
    "└───┬──────────────┬──────┘",
    "    │ uses         │ uses",
    "┌───▼──────────┐ ┌▼────────────────┐",
    "│FoodOrder     │ │DishMapper       │",
    "│Mapper        │ │(库存条件扣减)    │",
    "└──────────────┘ └─────────────────┘",
    "",
    "5.2 关键时序图",
    "",
    "【时序图1：创建订单 + 支付 完整调用链】",
    "",
    "  OrderController     OrderService      DishMapper    PaymentService    PaymentRecordMapper",
    "       │                   │                 │               │                 │",
    "       │ create(req,user)  │                 │               │                 │",
    "       │──────────────────>│                 │               │                 │",
    "       │                   │ validateDish()  │               │                 │",
    "       │                   │ for each item:  │               │                 │",
    "       │                   │────────────────>│               │                 │",
    "       │                   │<─── dish entity │               │                 │",
    "       │                   │                 │               │                 │",
    "       │                   │ stock >= qty?   │               │                 │",
    "       │                   │ UPDATE dish     │               │                 │",
    "       │                   │ SET stock=stock-qty              │                 │",
    "       │                   │ WHERE id=? AND stock>=qty         │                 │",
    "       │                   │────────────────>│               │                 │",
    "       │                   │<──affected rows │               │                 │",
    "       │                   │                 │               │                 │",
    "       │                   │ INSERT food_order + items         │                 │",
    "       │                   │────────────────>│               │                 │",
    "       │                   │                 │               │                 │",
    "       │<── FoodOrder      │                 │               │                 │",
    "       │                   │                 │               │                 │",
    "       │ (用户发起支付)     │                 │               │                 │",
    "       │ sandboxPay(orderId,idempotencyKey,userId)            │                 │",
    "       │─────────────────────────────────────────────────────>│                 │",
    "       │                   │                 │  幂等查重       │                 │",
    "       │                   │                 │  SELECT BY key │                 │",
    "       │                   │                 │──────────────────────────────>│",
    "       │                   │                 │<─── null (no dup)              │",
    "       │                   │                 │               │                 │",
    "       │                   │                 │  INSERT payment_record          │",
    "       │                   │                 │──────────────────────────────>│",
    "       │                   │                 │               │                 │",
    "       │                   │                 │  UPDATE order SET status=PAID  │",
    "       │                   │                 │  UPDATE member_account SET     │",
    "       │                   │                 │  points = points + earned      │",
    "       │                   │                 │  INSERT points_transaction     │",
    "       │                   │                 │               │                 │",
    "       │<── PaymentRecord  │                 │               │                 │",
    "",
    "【时序图2：退款申请 + 审批流程】",
    "",
    "  CustomerController  CustomerService  RefundRequestMapper  StoreManagerController  StoreManagerService",
    "       │                   │                 │                    │                      │",
    "       │ refund(orderId,   │                 │                    │                      │",
    "       │   reason, amount) │                 │                    │                      │",
    "       │──────────────────>│                 │                    │                      │",
    "       │                   │ 校验: 订单归属?  │                    │                      │",
    "       │                   │ 状态可退款?     │                    │                      │",
    "       │                   │ 未重复申请?     │                    │                      │",
    "       │                   │                 │                    │                      │",
    "       │                   │ INSERT refund   │                    │                      │",
    "       │                   │────────────────>│                    │                      │",
    "       │<── RefundRequest  │                 │                    │                      │",
    "       │   (REQUESTED)     │                 │                    │                      │",
    "       │                   │                 │                    │                      │",
    "       │  ... 店长登录后 ... │                 │                    │                      │",
    "       │                   │                 │  GET /manager/refunds              │",
    "       │                   │                 │───────────────────>│                 │",
    "       │                   │                 │<───退款申请列表     │                 │",
    "       │                   │                 │                    │                 │",
    "       │                   │                 │  approve/reject    │                 │",
    "       │                   │                 │───────────────────>│                 │",
    "       │                   │                 │                    │ 校验门店归属     │",
    "       │                   │                 │                    │ 校验当前状态     │",
    "       │                   │                 │                    │ UPDATE refund   │",
    "       │                   │                 │                    │ UPDATE order    │",
    "       │                   │                 │<───审批结果         │                 │"
])

cs(doc.tables[18].cell(0,0),
    "以上类图与时序图从静态结构和动态交互两个维度描述了核心模块的设计，为编码实现提供精确的调用链参考。")

# Section 6: 异常处理与并发设计 (T19)
cm(doc.tables[19].cell(0,0), [
    "6 异常处理与并发设计",
    "",
    "异常处理策略：",
    "• 全局异常拦截：GlobalExceptionHandler (@RestControllerAdvice) 统一将所有异常转换为 ApiResult 格式",
    "• 业务异常：Service 层抛出 BizException(code, message)，Controller 层不 try-catch",
    "• HTTP 状态码约定：",
    "  - 业务异常 → 400 Bad Request + ApiResult（code=业务码）",
    "  - 参数校验失败 → 400 Bad Request + ApiResult（字段级错误）",
    "  - 鉴权失败 → 401 Unauthorized / 403 Forbidden",
    "  - 系统异常 → 500 Internal Server Error + ApiResult（code=5000）",
    "",
    "并发控制策略：",
    "• 预约库存：乐观锁（version 字段 + 条件更新），冲突后提示用户重试",
    "• 菜品库存：条件更新（WHERE stock >= quantity），事务中原子执行，失败回滚",
    "• 支付幂等：idempotencyKey 唯一索引 + 业务查重（SELECT before INSERT）",
    "• 积分扣减：在支付事务中同步执行，与支付状态保持一致性",
    "• 活动领取：activity_claim 表唯一索引（userId + activityId）防重",
    "",
    "事务管理：",
    "• 使用 Spring @Transactional 注解",
    "• 事务边界在 Service 层方法上",
    "• 只读查询使用 @Transactional(readOnly = true)",
    "• 多表操作（订单+菜品库存扣减）在同一事务中执行",
    "• 外部 API 调用（AI 推荐）不在事务中执行",
    "",
    "重试策略：",
    "• 乐观锁冲突：前端提示用户重试，不自动重试（避免雪崩）",
    "• AI API 调用超时：一次重试（2s 超时），失败后 fallback",
    "• 数据库连接超时：HikariCP 连接池自动重试获取连接"
])

# Section 7: 单元测试设计要点 (T20)
cm(doc.tables[20].cell(0,0), [
    "7 单元测试设计要点",
    "",
    "每个核心模块的测试策略与关键用例点：",
    "",
    "┌─────────────────┬──────────────────────────────────┬────────────────────┐",
    "│ 测试类           │ 覆盖重点                          │ Mock 边界            │",
    "├─────────────────┼──────────────────────────────────┼────────────────────┤",
    "│ Reservation     │ 创建预约成功、人数超容量失败、      │ Mock Mapper 层      │",
    "│ ServiceTest     │ 时段库存不足失败、取消恢复库存、    │ 验证 UPDATE 条件    │",
    "│                 │ 并发冲突重试                      │                    │",
    "├─────────────────┼──────────────────────────────────┼────────────────────┤",
    "│ OrderServiceTest│ 创建订单成功、菜品库存不足失败、    │ Mock Mapper 层      │",
    "│                 │ 菜品下架不可点、优惠券抵扣计算、    │ 验证库存条件扣减    │",
    "│                 │ 并发下单不超卖                    │                    │",
    "├─────────────────┼──────────────────────────────────┼────────────────────┤",
    "│ PaymentService  │ 沙箱支付成功、重复支付幂等返回、    │ Mock Mapper 层      │",
    "│ Test            │ 非本人订单不可支付、积分正确发放、  │ 验证幂等键查重      │",
    "│                 │ 会员等级更新逻辑                  │                    │",
    "├─────────────────┼──────────────────────────────────┼────────────────────┤",
    "│ AuthServiceTest │ 注册成功、用户名重复失败、          │ Mock Mapper 层      │",
    "│                 │ 登录成功、密码错误失败、            │ 验证 BCrypt 匹配    │",
    "│                 │ JWT Token 包含正确角色、           │ 验证 Token 生成     │",
    "│                 │ 停用账号不可登录                  │                    │",
    "├─────────────────┼──────────────────────────────────┼────────────────────┤",
    "│ Customer        │ 积分查询、兑换奖励扣减积分、        │ Mock Mapper 层      │",
    "│ ServiceTest     │ 重复兑换拦截、退款申请创建、        │ 验证唯一索引冲突    │",
    "│                 │ 重复退款拦截、评价创建              │                    │",
    "├─────────────────┼──────────────────────────────────┼────────────────────┤",
    "│ StaffServiceTest│ 预约签到（门店归属校验）、          │ Mock Mapper 层      │",
    "│                 │ 订单开始制作（状态校验）、          │ 验证门店权限        │",
    "│                 │ 非本门店操作被拒绝、               │                    │",
    "│                 │ 排队叫号与入座状态流转              │                    │",
    "├─────────────────┼──────────────────────────────────┼────────────────────┤",
    "│ Recommend       │ 规则推荐排序正确性、               │ Mock Mapper 层      │",
    "│ ServiceTest     │ 无偏好时默认排序、                  │ Mock AI Client      │",
    "│                 │ AI 不可用 fallback 模板文案、       │                    │",
    "│                 │ 空门店列表返回空                    │                    │",
    "└─────────────────┴──────────────────────────────────┴────────────────────┘",
    "",
    "覆盖率目标：",
    "• 整体覆盖率 ≥ 60%（JaCoCo 行覆盖率）",
    "• 核心域（ReservationService / OrderService / PaymentService）≥ 80%",
    "• 前端最低限度测试：登录页渲染、门店列表渲染、预约创建关键状态",
    "",
    "Mock 原则：",
    "• Service 层测试 Mock 所有 Mapper 依赖（单元测试隔离数据库）",
    "• 使用 Mockito @Mock + @InjectMocks",
    "• 验证方法调用次数和参数（Mockito.verify）",
    "• 对乐观锁冲突场景，Mock Mapper 返回 affected_rows=0"
])

doc.save(DST)
print(f"D-04 saved to {DST}")
